#!/bin/bash

if ! [ -x "$(command -v pnpm)" ]; then
    echo '❗️ Error: pnpm is not installed.' >&2
    exit 1
else
    echo '📦 Running npm install...'
    pnpm install
fi

if ! [ -x "$(command -v composer)" ]; then
    echo '❗️ Error: composer is not installed.' >&2
    exit 1
else
    echo '🎼 Running composer install...'
    cd public && composer install && cd ..
fi

if ! [ -x "$(command -v valet)" ]; then
    echo '❗️ Error: valet is not installed.' >&2
    exit 1
else
    parked=$(valet parked)
    if [[ "$parked" == *$PWD* ]]; then
        echo "🚗 Site is already parked."
    else
        echo "🔗 Linking site..."
        valet link
    fi

    echo '🔐 Issuing certificate...'
    valet secure
fi


# create env file
cd public/
if test -f .env; then
    echo ".env file is present in public folder."
else
    if test -f .env.example; then
        cp .env.example .env
    else
        echo "KEY=value" > .env
    fi
fi
cd ..

if test -f .env; then
    echo ".env file is present in root directory."
else
    if test -f .env.example; then
        cp .env.example .env
    else
        echo "KEY=value" > .env
    fi
fi

# set site title
while true; do
    read -p "💬 What's the site called? " -r title
    php config/scripts/siteTitle.php $title
    ret=$?
    if [ $ret -eq 0 ]; then
        break
    fi
done

# valet
tld=$(valet tld)
sitename=$(basename "$PWD")
accountcount=$(find public/site/accounts -maxdepth 1 -type d | wc -l)

# create local config
cd public/site/config
if test -f config.$sitename.$tld.php; then
    "config file exists"
else
    mv config.example.test.php config.$sitename.$tld.php
    echo "local config file for $sitename.$tld created"
fi
cd ../../..

# create account
if [[ "$accountcount" -eq 1 ]]; then
    echo '✅ All set up!'
    echo "Local test site: https://$sitename.$tld/"
    echo
    read -p "👤 Do you want to create an admin user? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        while true; do
            read -p "email: " -r email
            read -p "password: " -r -s password
            echo
            php config/scripts/createAdmin.php $email $password
            ret=$?
            if [ $ret -eq 0 ]; then
                break
            fi
        done
        echo '✅ Panel installed!'
    else
        'Ok. You can manually install the panel here:'
    fi
    echo "https://$sitename.$tld/panel"
else
    echo "The panel is installed."
    echo "✅ All done!" 
    echo "Local test site: https://$sitename.$tld/"
fi

exit 0